name: mailing_system
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  sqflite: ^2.2.2
  file_picker:
  badges: ^2.0.3
  anim_search_bar: ^2.0.2
  google_nav_bar: ^5.0.6
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
  flutter_slidable: ^2.0.0
  line_awesome_flutter: ^2.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets: 
    - assets/images/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin-Italic.ttf
          weight: 700
    - family: Signa
      fonts:
        - asset: assets/fonts/SignikaNegative-Regular.ttf
        - asset: assets/fonts/SignikaNegative-Bold.ttf
          weight: 900
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
        - asset: assets/fonts/SourceSansPro-Black.ttf
          style: italic
          weight: 900
  uses-material-design: true
  
